
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rails-democv_development

test:
  <<: *default
  database: rails-democv_test


production:
  <<: *default
  database: rails-democv_production



