# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05db155da5e63cfb365d884d199e5ba8d9044e86327e6af49d6846880dcc4643adf72e65b6f2fa62b2f24e2430d15dcc1f5524a9587af56700a42ccad1d39cb5

test:
  secret_key_base: bbac62d069f6077188363ff24cf0f01d575623324677b18ed082d5db51db2195eb3b9a351b4a6f04f463802f6e8e92133111c996db8093633e24057513af94d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
